### ISSUE TITLE
502s and readiness check failrues

### ISSUE THREAD

**Issue by jlewi** [hamelsmu/MLapp#27] opened 2019-04-15 21:07 UTC
@hamelsmu is reporting occasional 502s.

I'm noticing that most of the pods aren't reporting a steady health metric

```
kubectl -n mlapp get pods
NAME                             READY     STATUS    RESTARTS   AGE
ml-github-app-86676c7c4c-2tphc   0/1       Running   0          17m
ml-github-app-86676c7c4c-57ssv   0/1       Running   0          17m
ml-github-app-86676c7c4c-h8wlb   0/1       Running   0          17m
ml-github-app-86676c7c4c-ljz9w   0/1       Running   0          10h
ml-github-app-86676c7c4c-lr2jx   0/1       Running   0          17m
ml-github-app-86676c7c4c-p2jzp   0/1       Running   0          17m
ml-github-app-86676c7c4c-xc2jg   0/1       Running   0          10h
ml-github-app-86676c7c4c-xhcgs   1/1       Running   0          17m
ml-github-app-86676c7c4c-xzg44   0/1       Running   0          10h
jlewi@jlewi-carbon-glaptop:~/git_kubeflow-testing/test-infra/ks_app$ kubectl -n mlapp get pods
NAME                             READY     STATUS    RESTARTS   AGE
ml-github-app-86676c7c4c-2tphc   0/1       Running   0          17m
ml-github-app-86676c7c4c-57ssv   0/1       Running   0          17m
ml-github-app-86676c7c4c-h8wlb   0/1       Running   0          17m
ml-github-app-86676c7c4c-ljz9w   1/1       Running   0          10h
ml-github-app-86676c7c4c-lr2jx   1/1       Running   0          17m
ml-github-app-86676c7c4c-p2jzp   0/1       Running   0          17m
ml-github-app-86676c7c4c-xc2jg   0/1       Running   0          10h
ml-github-app-86676c7c4c-xhcgs   0/1       Running   0          17m
ml-github-app-86676c7c4c-xzg44   0/1       Running   0          10h
jlewi@jlewi-carbon-glaptop:~/git_kubeflow-testing/test-infra/ks_app$ kubectl -n mlapp get pods
NAME                             READY     STATUS    RESTARTS   AGE
ml-github-app-86676c7c4c-2tphc   0/1       Running   0          17m
ml-github-app-86676c7c4c-57ssv   0/1       Running   0          17m
ml-github-app-86676c7c4c-h8wlb   0/1       Running   0          17m
ml-github-app-86676c7c4c-ljz9w   0/1       Running   0          10h
ml-github-app-86676c7c4c-lr2jx   1/1       Running   0          17m
ml-github-app-86676c7c4c-p2jzp   0/1       Running   0          17m
ml-github-app-86676c7c4c-xc2jg   1/1       Running   0          10h
ml-github-app-86676c7c4c-xhcgs   0/1       Running   0          17m
ml-github-app-86676c7c4c-xzg44   0/1       Running   0          10h

```

**Comment by hamelsmu** [comment] 2019-04-15 21:19
Thanks Jeremy, root cause seems to be:

- The front page of the app is making a request to the GitHub API to server real-time stats.  
- K8 cluster has a load balancer that is constantly pinging the front page of the app for health checks
- This causes the GitHub API to tell me I'm abusing their service because creating tons of requests per second.  

Short Term Fix:
 - I'm removing GitHub API dependencies from front page load.

Long Term Fix:
- Have a special route for just health check that is not the front page
- Install Gunicorn 

Thanks for your help everyone @hohsiangwu, @inc0 and @jlewi

**Comment by hamelsmu** [comment] 2019-04-18 11:37
Closing because this was resolved

**Closed by hamelsmu** 2019-04-18 11:37 UTC
Labels: kind/bug
